using Microsoft.Data.SqlClient;
using RFQ.Domain.Enums;
using RFQ.Domain.Helper;
using RFQ.Domain.Interfaces;
using RFQ.Domain.RequestDto;
using System.Data;
using System.Drawing.Printing;
using System.Xml.Linq;

namespace RFQ.Infrastructure.Efcore.Providers
{
    public class CommonRepositroy : ICommonRepositroy
    {
        private readonly IFleetLynkAdo _fleetLynkAdo;

        public CommonRepositroy(IFleetLynkAdo fleetLynkAdo)
        {
            _fleetLynkAdo = fleetLynkAdo;
        }


        public async Task<PageList<T>> GetAllRecordsFromStoredProcedure<T>(string SpName, PagingParam pagingParam) where T : class, new()
        {
            var statusId = (int)EStatus.IsActive;
            var pageNumber = (pagingParam.Start / pagingParam.Length) + 1;
            var pageSize = pagingParam.Length;

            var searchTerm = string.IsNullOrEmpty(pagingParam.SearchValue) ? (object)DBNull.Value : pagingParam.SearchValue;
            var sortColumn = string.IsNullOrEmpty(pagingParam.OrderColumn) ? (object)DBNull.Value : pagingParam.OrderColumn;
            var sortDirection = string.IsNullOrEmpty(pagingParam.OrderDir) ? (object)DBNull.Value : pagingParam.OrderDir;

            var parameters = new List<SqlParameter>
            {
                new SqlParameter("@CompanyId", SqlDbType.Int) { Value = pagingParam.CompanyId },
                new SqlParameter("@StatusId", SqlDbType.Int) { Value = statusId },
                new SqlParameter("@PageNumber", SqlDbType.Int) { Value = pageNumber },
                new SqlParameter("@PageSize", SqlDbType.Int) { Value = pageSize },
                new SqlParameter("@SearchTerm", SqlDbType.NVarChar, 100) { Value = searchTerm },
                new SqlParameter("@SortColumn", SqlDbType.NVarChar, 50) { Value = sortColumn },
                new SqlParameter("@SortDirection", SqlDbType.NVarChar, 4) { Value = sortDirection }
            };

            var dataTable = await _fleetLynkAdo.ExecuteStoredProcedureAsync(
                SpName, parameters
            );
            var items = DataTableMapper.MapToList<T>(dataTable);

            int totalCount = dataTable.Columns.Contains("TotalCount") && dataTable.Rows.Count > 0
                ? Convert.ToInt32(dataTable.Rows[0]["TotalCount"])
                : items.Count;

            return new PageList<T>(items, totalCount, pageNumber, pageSize);
        }

        public async Task<string> GetAutoGenerateCode(AutoGenerateCodeRequestDto requestDto)
        {
            try
            {
                var code = string.Empty;
                if (requestDto.Prefix == PrefixCode.VI)
                {
                    var parameters = new List<SqlParameter>
                        {
                            new SqlParameter("@UserId ", SqlDbType.Int) { Value = requestDto.UserId },
                            new SqlParameter("@Code", SqlDbType.NVarChar, 500) { Value = requestDto.Code },
                            new SqlParameter("@Prefix", SqlDbType.NVarChar, 500) { Value = requestDto.Prefix },
                        };

                    var dataTable = await _fleetLynkAdo.ExecuteStoredProcedureAsync(
                        StoredProcedureHelper.sp_VehicleIndentAutoGenerateCode, parameters
                    );
                    return  (string)dataTable.Rows[0]["AutoGeneratedCode"];
                }
                if (requestDto.Prefix == PrefixCode.RFQ)
                {
                    var parameters = new List<SqlParameter>
                        {
                            new SqlParameter("@UserId ", SqlDbType.Int) { Value = requestDto.UserId },
                            new SqlParameter("@Code", SqlDbType.NVarChar, 500) { Value = requestDto.Code },
                            new SqlParameter("@Prefix", SqlDbType.NVarChar, 500) { Value = requestDto.Prefix },
                        };

                    var dataTable = await _fleetLynkAdo.ExecuteStoredProcedureAsync(
                        StoredProcedureHelper.sp_RfqAutoGenerateCode, parameters
                    );
                    return (string)dataTable.Rows[0]["AutoGeneratedCode"];
                }
                if (requestDto.Prefix == PrefixCode.VP)
                {
                    var parameters = new List<SqlParameter>
                        {
                            new SqlParameter("@UserId ", SqlDbType.Int) { Value = requestDto.UserId },
                            new SqlParameter("@Code", SqlDbType.NVarChar, 500) { Value = requestDto.Code },
                            new SqlParameter("@Prefix", SqlDbType.NVarChar, 500) { Value = requestDto.Prefix },
                        };

                    var dataTable = await _fleetLynkAdo.ExecuteStoredProcedureAsync(
                        StoredProcedureHelper.sp_PlacementAutoGenerateCode, parameters
                    );
                    return (string)dataTable.Rows[0]["AutoGeneratedCode"];
                }
                if (requestDto.Prefix == PrefixCode.LR)
                {
                    var parameters = new List<SqlParameter>
                        {
                            new SqlParameter("@UserId ", SqlDbType.Int) { Value = requestDto.UserId },
                            new SqlParameter("@Code", SqlDbType.NVarChar, 500) { Value = requestDto.Code },
                            new SqlParameter("@Prefix", SqlDbType.NVarChar, 500) { Value = requestDto.Prefix },
                        };

                    var dataTable = await _fleetLynkAdo.ExecuteStoredProcedureAsync(
                        StoredProcedureHelper.sp_LRNoAutoGenerateCode, parameters
                    );
                    return (string)dataTable.Rows[0]["AutoGeneratedCode"];
                }
                return null;
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}
